- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: "devops with aws"
    DURATION: "140hrs"
    TRAINER: "sivakumar"
  tasks: 
  - name: print variabls
    ansible.builtin.debug:
      msg: "course is: {{ COURSE }}, duration is {{ DURATION }}, trainer is: {{ TRAINER }}"
     