- name: file variables
  hosts: local
  connection: local
  vars_files:
  - course.yaml 
  tasks: 
  - name: print variabls
    vars: 
      COURSE: ansible
    ansible.builtin.debug:
      msg: "course is: {{ COURSE }}, duration is {{ DURATION }}, trainer is: {{ TRAINER }}"